### ISSUE TITLE
Composer create-project

### ISSUE THREAD

**Issue by normanlolx** [wodby/wordpress-composer#3]
Hey hey, so far this is my favorite WordPress Composer template due to its simplicity. Is there any reason this project didn't got published on https://packagist.org?

Would be really nice to simply be able to use `composer create-project wodby/wordpress-composer my-directory` to initiate a project instead of needing to clone this repo and then need to purge and re-initiate Git.

**Comment by csandanov** [comment]
Thanks for the suggestion, no specific reason

Just published https://packagist.org/packages/wodby/wordpress-composer

**Comment by normanlolx** [comment]
Would you like if I open a PR to update the README then?

**Comment by csandanov** [comment]
Yes, that would be great. I guess we can add something similar from https://github.com/drupal-composer/drupal-project
