### ISSUE TITLE
Question: What is the intended method to use with docker4wordpress

### ISSUE THREAD

**Issue by brandonkal** [wodby/wordpress-composer#6]
Looking at the docker4wordpress stack, I see that the php image has composer and wp-cli already installed. However, if I bind mount just the web directory, composer will not have access to the composer.json. But if I were to mount the whole wordpress-composer project, then those files are in the web root and served by nginx, which is not ideal.

For local development on my mac, installing php and composer is simple enough. But I would also like to experiment with developing inside a virtual machine such as vagrant where I will not have php and composer available on the base system. For that use case I currently see two approaches but if there is another, please advise:

1. Launch another php container that bind mounts to the wordpress-composer directory. Use this container to run composer install.
2. Bind mount php container to /var/www and change web to html in wordpress-composer. Nginx container would be bind mounted to /var/www/html. Not sure how well that would work.

Thank you, and awesome work as always.

**Comment by csandanov** [comment]
When you mount a project dir and have WP root under `web/` you should add env var `NGINX_SERVER_ROOT=/var/www/html/web` to nginx

**Comment by brandonkal** [comment]
Oh wow, that is elegant! So I can set that and bind mount /var/www/html to both nginx and wordpress?

**Comment by csandanov** [comment]
yes, it should be the same

**Comment by brandonkal** [comment]
I see the containers use a lot of environment variables. If I wanted the wordpress uploads folder to be a seperate bind mount is there an extra env var I need to set so it will work with nginx besides the wp-config.php change?

**Comment by csandanov** [comment]
At Wodby we use a symlink for that for uploads dir to a separate bind mount
